--[[
	******************************************************************************
	* @name			:	promise-plusplus
	* @authors		:	Cod2rDude
	* @date			:	January 7 2026
	* @lastEdit		:	January 7 2026
	* @brief		:	A lightweight promise library.
	* @version		:	0.0.1
	******************************************************************************
	* @attention
	*
	* Copyright © 2026 Axon Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--// Libs
local libs = script.libs

--promise-plusplus.src.__index
return require(libs.constructor)